# Site settings
title: Blueskyatnight Web Design + Development Studio - Perth
email: darcy@blueskyatnight.com.au
description: > # this means to ignore newlines until "baseurl:"
  Blueskyatnight are web design + development specialists who use design and technology to transform ideas, businesses and brands.
baseurl: ""
url: "http://blueskyatnight.com.au"

relative_permalinks: false

twitter_username:
github_username: darcemac
name: Darcy McDonald

locale: en-AU

# Build settings
markdown: kramdown

permalink: /projects/:title/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  endings: all
  ignore:
    envs: [local]

exclude: ["node_modules", "gulpfile.js", "package.json"]
